management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: resolog

  datasource:
    url: jdbc:h2:mem:resolve
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
